//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSettings
    {
        public int ID { get; set; }
        public string SmtpServer { get; set; }
        public string MailSubject { get; set; }
        public string FromMail { get; set; }
        public string ToMail { get; set; }
        public string FromMailPassword { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> UserLoginID { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
